scrape_configs:
 - job_name: 'csvserver_records'
   honor_timestamps: true
   scrape_interval: 5m
   scrape_timeout: 10s
   metrics_path: /metrics
   scheme: http
   static_configs:
      - targets: ['localhost:9393']
